<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pedido [

  <!ELEMENT pedido (libro* | cuaderno* | lapiz*)+>
  <!ELEMENT libro EMPTY>
  <!ATTLIST libro titulo CDATA #REQUIRED>

  <!ELEMENT cuaderno EMPTY>
  <!ATTLIST cuaderno num_hojas CDATA #IMPLIED>
  <!ELEMENT lapiz (numero)>
  <!ELEMENT numero (#PCDATA)>
]>

<pedido>
  <libro titulo="El Quijote"/>
  <cuaderno num_hojas="100"/>
  <lapiz>
    <numero>3</numero>
  </lapiz>
  <libro titulo="Cien aÃ±os de soledad"/>
  <lapiz>
    <numero>1</numero>
  </lapiz>
  <lapiz>
    <numero>2</numero>
  </lapiz>
  <cuaderno/>
</pedido> 
