<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE lista_cursos [

  <!ELEMENT lista_cursos (curso+)>
  <!ELEMENT curso (alumno+)>
  <!ELEMENT alumno (DNI,nombre,apellido,segundo_apellido?,lista_asignaturas)>

  <!ELEMENT DNI (#PCDATA)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
  <!ELEMENT segundo_apellido (#PCDATA)>

  <!ELEMENT lista_asignaturas (asignatura+)>
  <!ELEMENT asignatura (nombre,profesor)>
  <!ATTLIST asignatura codigo CDATA #REQUIRED
  <!ELEMENT profesor (NRP,nombre,apellido,segundo_apellido?)>
  <!ELEMENT NRP (#PCDATA)>
]>

<lista_cursos>

  <curso>

    <alumno>

      <DNI>54345678A</DNI>
      <nombre>Juan</nombre>
      <apellido>Perez</apellido>

      <lista_asignaturas>

        <asignatura codigo="1234">
          <nombre>Biología</nombre>
          <profesor>
            <NRP>1122</NRP>
            <nombre>Laia</nombre>
            <apellido>Oro</apellido>
          </profesor>
        </asignatura>

      </lista_asignaturas>

    </alumno>

    <alumno>

      <DNI>33423789B</DNI>
      <nombre>Pedro</nombre>
      <apellido>Sánchez</apellido>
      <segundo_apellido>Gómez</segundo_apellido>
      <lista_asignaturas>

        <asignatura>

          <nombre>Matemáticas</nombre>
          <profesor>
            <NRP>1111</NRP>
            <nombre>Joana</nombre>
            <apellido>Pons</apellido>
          </profesor>
        </asignatura>

        <asignatura>
          <nombre>Inglés</nombre>
          <profesor>
            <NRP>3333</NRP>
            <nombre>Johne</nombre>
            <apellido>Smith</apellido>
          </profesor>

        </asignatura>

      </lista_asignaturas>

    </alumno>

  </curso>

  <curso>

    <alumno>

      <DNI>34543290C</DNI>
      <nombre>Lucía</nombre>
      <apellido>Rodríguez</apellido>

      <lista_asignaturas>

        <asignatura codigo="3245">
          <nombre>Física</nombre>
          <profesor>
            <NRP>4455</NRP>
            <nombre>Sebastià</nombre>
            <apellido>Pons</apellido>
            <segundo_apellido>Gomila</segundo_apellido>
          </profesor>
        </asignatura>

      </lista_asignaturas>

    </alumno>

  </curso>

</lista_cursos>
